export default {
    IHttpClient: Symbol.for('IHttpClient'),
    IAbbreviationResolver: Symbol.for('IAbbreviationResolver'),
    IRepositoryProvider: Symbol.for('IRepositoryProvider'),
    OutlookApiProvider: Symbol.for('OutlookApiProvider'),
    OutlookWebhookProvider: Symbol.for('OutlookWebhookProvider'),
    ZendeskTicketByMailProvider: Symbol.for('ZendeskTicketByMailProvider'),
    LanguageNameResolver: Symbol.for('LanguageNameResolver'),
    LicenseNameResolver: Symbol.for('LicenseNameResolver'),
    GithubWebhookProviderService: Symbol.for('GithubWebhookProviderService'),
    GithubCommitService: Symbol.for('GithubCommitService'),
    GithubPullRequestService: Symbol.for('GithubPullRequestService'),
    GithubRepositoryProvider: Symbol.for('GithubRepositoryProvider'),
    AzureDevopsWebhookProviderService: Symbol.for('AzureDevopsWebhookProviderService'),
    AzureDevopsCiBuildService: Symbol.for('AzureDevopsCiBuildService'),
    AzureDevopsCdReleaseService: Symbol.for('AzureDevopsCdReleaseService'),
    AzureDevopsApiProvider: Symbol.for('AzureDevopsApiProvider'),
    AzureDevopsPipelineProvider: Symbol.for('AzureDevopsPipelineProvider'),
    ResolverType: Symbol.for('ResolverType'),
    AppSettings: Symbol.for('AppSettings')
}
